:star: {asterisk}
:all: {asterisk}{asterisk}

[[_social_login_authserver]]
= Hosting an Authorization Server

In this section we modify the <<_social_login_github,github>> app we built by making the app into a fully-fledged OAuth2 Authorization Server, still using Facebook and Github for authentication, but able to create its own access tokens. These tokens could then be used to secure back end resources, or to do SSO with other applications that we happen to need to secure the same way.

== Testing the OAuth2 Client

To test the new features you can just run both apps and visit
http://localhost:9999/client in your browser. The client app will
redirect to the local Authorization Server, which then gives the user
the usual choice of authentication with Facebook or Github. Once that
is complete control returns to the test client, the local access token
is granted and authentication is complete (you should see a "Hello"
message in your browser). If you are already authenticated with Github
or Facebook you may not even notice the remote authentication.
